import { useParams, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import Navigation from '../../components/feature/Navigation';
import ContactFooter from '../contact/components/ContactFooter';
import StudioCTA from '../studio/components/StudioCTA';
import ProjectHero from './components/ProjectHero';
import ProjectInfo from './components/ProjectInfo';
import ProjectSpecs from './components/ProjectSpecs';
import ProjectLocation from './components/ProjectLocation';
import NextProject from './components/NextProject';

const projectSpecs: Record<string, { plotArea: string; builtArea: string; floors: string; typology: string }> = {
  'mallberry-platinum-hall-lounge': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Interior Design' },
  'abucay-beach-house': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Residential' },
  'amelia-nail-salon': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Interior Design' },
  'bacolod-showroom': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Retail' },
  'bc-cdo': { plotArea: '—', builtArea: '—', floors: '3', typology: 'Mixed Use' },
  'byd-cdo': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Retail' },
  'byd-tagum': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Retail' },
  'byd-zamboanga': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Retail' },
  'chiong-clinic': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Healthcare' },
  'chiu-office': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Offices' },
  'davao-showroom': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Retail' },
  'foxhome': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Residential' },
  'kaway-resort': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Hospitality' },
  'palm-residences': { plotArea: '—', builtArea: '—', floors: '3', typology: 'Residential' },
  'palm-sands': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Hospitality' },
  'rc-mandani-loft': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Residential' },
  'rosales-residence': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Residential' },
  'squareview': { plotArea: '—', builtArea: '—', floors: '4', typology: 'Mixed Use' },
  'vmc-admin': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Offices' },
  'vmc-housing': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Residential' },
  'vmc-projects': { plotArea: '—', builtArea: '—', floors: '3', typology: 'Mixed Use' },
  'choa-unit-16c': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Residential' },
  'graphic-junior-hotel': { plotArea: '—', builtArea: '—', floors: '4', typology: 'Hospitality' },
  'cafe-207': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Hospitality' },
  'byd-butuan': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Retail' },
  'byd-c5-acropolis': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Retail' },
  'byd-iligan': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Retail' },
  'byd-marikina': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Retail' },
  'balisbis-residence': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Residential' },
  'bellarie-office': { plotArea: '—', builtArea: '—', floors: '4', typology: 'Offices' },
  'blush': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Interior Design' },
  'dasmarinas-residence': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Residential' },
  'denza-showroom': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Retail' },
  'foxhomes-2025': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Residential' },
  'graphic-annex': { plotArea: '—', builtArea: '—', floors: '3', typology: 'Hospitality' },
  'ozamiz-dialysis-center': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Healthcare' },
  'raintree-beauty-clinic': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Interior Design' },
  'sanjus-diagnostics': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Healthcare' },
  'sorana-island-villas': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Hospitality' },
  'sytin-projects': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Retail' },
  'tabas': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Residential' },
  'vmc-projects-2025': { plotArea: '—', builtArea: '—', floors: '3', typology: 'Mixed Use' },
  'yang-residence': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Residential' },
  'yap-residences-interiors': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Residential' },
  'baic-radar-cdo': { plotArea: '—', builtArea: '—', floors: '1', typology: 'Retail' },
  'chen-residence': { plotArea: '—', builtArea: '—', floors: '2', typology: 'Residential' },
};

const projectsData = [
  {
    id: 1,
    slug: 'mallberry-platinum-hall-lounge',
    translationKey: 'mallberry_platinum_hall_lounge',
    year: '2023',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/mallberry-hero.webp',
    mainImage: '/images/projects/mallberry-main.webp',
    gallery: [
      '/images/projects/mallberry-1.webp',
      '/images/projects/mallberry-2.webp',
      '/images/projects/mallberry-3.webp',
      '/images/projects/mallberry-4.webp',
      '/images/projects/mallberry-5.webp',
      '/images/projects/mallberry-6.webp',
      '/images/projects/mallberry-7.webp',
      '/images/projects/mallberry-8.webp',
      '/images/projects/mallberry-9.webp',
      '/images/projects/mallberry-10.webp',
      '/images/projects/mallberry-11.webp',
      '/images/projects/mallberry-12.webp',
      '/images/projects/mallberry-13.webp',
      '/images/projects/mallberry-14.webp',
      '/images/projects/mallberry-15.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 2,
    slug: 'abucay-beach-house',
    translationKey: 'abucay_beach_house',
    year: '2024',
    location: 'Bataan',
    lat: 14.7270,
    lng: 120.5332,
    heroImage: '/images/projects/abucay-hero.webp',
    mainImage: '/images/projects/abucay-main.webp',
    gallery: [
      '/images/projects/abucay-1.webp',
      '/images/projects/abucay-2.webp',
      '/images/projects/abucay-3.webp',
      '/images/projects/abucay-4.webp',
      '/images/projects/abucay-5.webp',
      '/images/projects/abucay-6.webp',
      '/images/projects/abucay-7.webp',
      '/images/projects/abucay-8.webp',
      '/images/projects/abucay-9.webp',
      '/images/projects/abucay-10.webp',
      '/images/projects/abucay-11.webp',
      '/images/projects/abucay-12.webp',
      '/images/projects/abucay-13.webp',
      '/images/projects/abucay-14.webp',
      '/images/projects/abucay-15.webp',
      '/images/projects/abucay-16.webp',
      '/images/projects/abucay-17.webp',
      '/images/projects/abucay-18.webp',
      '/images/projects/abucay-19.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 3,
    slug: 'amelia-nail-salon',
    translationKey: 'amelia_nail_salon',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/amelia-nail-salon-hero.webp',
    mainImage: '/images/projects/amelia-nail-salon-main.webp',
    gallery: [
      '/images/projects/amelia-nail-salon-1.webp',
      '/images/projects/amelia-nail-salon-2.webp',
      '/images/projects/amelia-nail-salon-3.webp',
      '/images/projects/amelia-nail-salon-4.webp',
      '/images/projects/amelia-nail-salon-5.webp',
      '/images/projects/amelia-nail-salon-6.webp',
      '/images/projects/amelia-nail-salon-7.webp',
      '/images/projects/amelia-nail-salon-8.webp',
      '/images/projects/amelia-nail-salon-9.webp',
      '/images/projects/amelia-nail-salon-10.webp',
      '/images/projects/amelia-nail-salon-11.webp',
      '/images/projects/amelia-nail-salon-12.webp',
      '/images/projects/amelia-nail-salon-13.webp',
      '/images/projects/amelia-nail-salon-14.webp',
      '/images/projects/amelia-nail-salon-15.webp',
      '/images/projects/amelia-nail-salon-16.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 4,
    slug: 'bacolod-showroom',
    translationKey: 'bacolod_showroom',
    year: '2024',
    location: 'Bacolod',
    lat: 10.6768,
    lng: 122.9564,
    heroImage: '/images/projects/bacolod-showroom-hero.webp',
    mainImage: '/images/projects/bacolod-showroom-main.webp',
    gallery: [
      '/images/projects/bacolod-showroom-1.webp',
      '/images/projects/bacolod-showroom-2.webp',
      '/images/projects/bacolod-showroom-3.webp',
      '/images/projects/bacolod-showroom-4.webp',
      '/images/projects/bacolod-showroom-5.webp',
      '/images/projects/bacolod-showroom-6.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 5,
    slug: 'bc-cdo',
    translationKey: 'bc_cdo',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/bc-cdo-hero.webp',
    mainImage: '/images/projects/bc-cdo-main.webp',
    gallery: [
      '/images/projects/bc-cdo-1.webp',
      '/images/projects/bc-cdo-2.webp',
      '/images/projects/bc-cdo-3.webp',
      '/images/projects/bc-cdo-4.webp',
      '/images/projects/bc-cdo-5.webp',
      '/images/projects/bc-cdo-6.webp',
      '/images/projects/bc-cdo-7.webp',
      '/images/projects/bc-cdo-8.webp',
      '/images/projects/bc-cdo-9.webp',
      '/images/projects/bc-cdo-10.webp',
      '/images/projects/bc-cdo-11.webp',
      '/images/projects/bc-cdo-12.webp',
      '/images/projects/bc-cdo-13.webp',
      '/images/projects/bc-cdo-14.webp',
      '/images/projects/bc-cdo-15.webp',
      '/images/projects/bc-cdo-16.webp',
      '/images/projects/bc-cdo-17.webp',
      '/images/projects/bc-cdo-18.webp',
      '/images/projects/bc-cdo-19.webp',
      '/images/projects/bc-cdo-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 6,
    slug: 'byd-cdo',
    translationKey: 'byd_cdo',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/byd-cdo-hero.webp',
    mainImage: '/images/projects/byd-cdo-main.webp',
    gallery: [
      '/images/projects/byd-cdo-1.webp',
      '/images/projects/byd-cdo-2.webp',
      '/images/projects/byd-cdo-3.webp',
      '/images/projects/byd-cdo-4.webp',
      '/images/projects/byd-cdo-5.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 7,
    slug: 'byd-tagum',
    translationKey: 'byd_tagum',
    year: '2024',
    location: 'Tagum',
    lat: 7.4478,
    lng: 125.8086,
    heroImage: '/images/projects/byd-tagum-hero.webp',
    mainImage: '/images/projects/byd-tagum-main.webp',
    gallery: [
      '/images/projects/byd-tagum-1.webp',
      '/images/projects/byd-tagum-2.webp',
      '/images/projects/byd-tagum-3.webp',
      '/images/projects/byd-tagum-4.webp',
      '/images/projects/byd-tagum-5.webp',
      '/images/projects/byd-tagum-6.webp',
      '/images/projects/byd-tagum-7.webp',
      '/images/projects/byd-tagum-8.webp',
      '/images/projects/byd-tagum-9.webp',
      '/images/projects/byd-tagum-10.webp',
      '/images/projects/byd-tagum-11.webp',
      '/images/projects/byd-tagum-12.webp',
      '/images/projects/byd-tagum-13.webp',
      '/images/projects/byd-tagum-14.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 8,
    slug: 'byd-zamboanga',
    translationKey: 'byd_zamboanga',
    year: '2024',
    location: 'Zamboanga',
    lat: 6.9214,
    lng: 122.079,
    heroImage: '/images/projects/byd-zamboanga-hero.webp',
    mainImage: '/images/projects/byd-zamboanga-main.webp',
    gallery: [
      '/images/projects/byd-zamboanga-1.webp',
      '/images/projects/byd-zamboanga-2.webp',
      '/images/projects/byd-zamboanga-3.webp',
      '/images/projects/byd-zamboanga-4.webp',
      '/images/projects/byd-zamboanga-5.webp',
      '/images/projects/byd-zamboanga-6.webp',
      '/images/projects/byd-zamboanga-7.webp',
      '/images/projects/byd-zamboanga-8.webp',
      '/images/projects/byd-zamboanga-9.webp',
      '/images/projects/byd-zamboanga-10.webp',
      '/images/projects/byd-zamboanga-11.webp',
      '/images/projects/byd-zamboanga-12.webp',
      '/images/projects/byd-zamboanga-13.webp',
      '/images/projects/byd-zamboanga-14.webp',
      '/images/projects/byd-zamboanga-15.webp',
      '/images/projects/byd-zamboanga-16.webp',
      '/images/projects/byd-zamboanga-17.webp',
      '/images/projects/byd-zamboanga-18.webp',
      '/images/projects/byd-zamboanga-19.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 9,
    slug: 'chiong-clinic',
    translationKey: 'chiong_clinic',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/chiong-clinic-hero.webp',
    mainImage: '/images/projects/chiong-clinic-main.webp',
    gallery: [
      '/images/projects/chiong-clinic-1.webp',
      '/images/projects/chiong-clinic-2.webp',
      '/images/projects/chiong-clinic-3.webp',
      '/images/projects/chiong-clinic-4.webp',
      '/images/projects/chiong-clinic-5.webp',
      '/images/projects/chiong-clinic-6.webp',
      '/images/projects/chiong-clinic-7.webp',
      '/images/projects/chiong-clinic-8.webp',
      '/images/projects/chiong-clinic-9.webp',
      '/images/projects/chiong-clinic-10.webp',
      '/images/projects/chiong-clinic-11.webp',
      '/images/projects/chiong-clinic-12.webp',
      '/images/projects/chiong-clinic-13.webp',
      '/images/projects/chiong-clinic-14.webp',
      '/images/projects/chiong-clinic-15.webp',
      '/images/projects/chiong-clinic-16.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 10,
    slug: 'chiu-office',
    translationKey: 'chiu_office',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/chiu-office-hero.webp',
    mainImage: '/images/projects/chiu-office-main.webp',
    gallery: [
      '/images/projects/chiu-office-1.webp',
      '/images/projects/chiu-office-2.webp',
      '/images/projects/chiu-office-3.webp',
      '/images/projects/chiu-office-4.webp',
      '/images/projects/chiu-office-5.webp',
      '/images/projects/chiu-office-6.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 11,
    slug: 'davao-showroom',
    translationKey: 'davao_showroom',
    year: '2024',
    location: 'Davao',
    lat: 7.1907,
    lng: 125.4553,
    heroImage: '/images/projects/davao-showroom-hero.webp',
    mainImage: '/images/projects/davao-showroom-main.webp',
    gallery: [
      '/images/projects/davao-showroom-1.webp',
      '/images/projects/davao-showroom-2.webp',
      '/images/projects/davao-showroom-3.webp',
      '/images/projects/davao-showroom-4.webp',
      '/images/projects/davao-showroom-5.webp',
      '/images/projects/davao-showroom-6.webp',
      '/images/projects/davao-showroom-7.webp',
      '/images/projects/davao-showroom-8.webp',
      '/images/projects/davao-showroom-9.webp',
      '/images/projects/davao-showroom-10.webp',
      '/images/projects/davao-showroom-11.webp',
      '/images/projects/davao-showroom-12.webp',
      '/images/projects/davao-showroom-13.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 12,
    slug: 'foxhome',
    translationKey: 'foxhome',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/foxhome-hero.webp',
    mainImage: '/images/projects/foxhome-main.webp',
    gallery: [
      '/images/projects/foxhome-1.webp',
      '/images/projects/foxhome-2.webp',
      '/images/projects/foxhome-3.webp',
      '/images/projects/foxhome-4.webp',
      '/images/projects/foxhome-5.webp',
      '/images/projects/foxhome-6.webp',
      '/images/projects/foxhome-7.webp',
      '/images/projects/foxhome-8.webp',
      '/images/projects/foxhome-9.webp',
      '/images/projects/foxhome-10.webp',
      '/images/projects/foxhome-11.webp',
      '/images/projects/foxhome-12.webp',
      '/images/projects/foxhome-13.webp',
      '/images/projects/foxhome-14.webp',
      '/images/projects/foxhome-15.webp',
      '/images/projects/foxhome-16.webp',
      '/images/projects/foxhome-17.webp',
      '/images/projects/foxhome-18.webp',
      '/images/projects/foxhome-19.webp',
      '/images/projects/foxhome-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 13,
    slug: 'kaway-resort',
    translationKey: 'kaway_resort',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/kaway-resort-hero.webp',
    mainImage: '/images/projects/kaway-resort-main.webp',
    gallery: [
      '/images/projects/kaway-resort-1.webp',
      '/images/projects/kaway-resort-2.webp',
      '/images/projects/kaway-resort-3.webp',
      '/images/projects/kaway-resort-4.webp',
      '/images/projects/kaway-resort-5.webp',
      '/images/projects/kaway-resort-6.webp',
      '/images/projects/kaway-resort-7.webp',
      '/images/projects/kaway-resort-8.webp',
      '/images/projects/kaway-resort-9.webp',
      '/images/projects/kaway-resort-10.webp',
      '/images/projects/kaway-resort-11.webp',
      '/images/projects/kaway-resort-12.webp',
      '/images/projects/kaway-resort-13.webp',
      '/images/projects/kaway-resort-14.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 14,
    slug: 'palm-residences',
    translationKey: 'palm_residences',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/palm-residences-hero.webp',
    mainImage: '/images/projects/palm-residences-main.webp',
    gallery: [
      '/images/projects/palm-residences-1.webp',
      '/images/projects/palm-residences-2.webp',
      '/images/projects/palm-residences-3.webp',
      '/images/projects/palm-residences-4.webp',
      '/images/projects/palm-residences-5.webp',
      '/images/projects/palm-residences-6.webp',
      '/images/projects/palm-residences-7.webp',
      '/images/projects/palm-residences-8.webp',
      '/images/projects/palm-residences-9.webp',
      '/images/projects/palm-residences-10.webp',
      '/images/projects/palm-residences-11.webp',
      '/images/projects/palm-residences-12.webp',
      '/images/projects/palm-residences-13.webp',
      '/images/projects/palm-residences-14.webp',
      '/images/projects/palm-residences-15.webp',
      '/images/projects/palm-residences-16.webp',
      '/images/projects/palm-residences-17.webp',
      '/images/projects/palm-residences-18.webp',
      '/images/projects/palm-residences-19.webp',
      '/images/projects/palm-residences-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 15,
    slug: 'palm-sands',
    translationKey: 'palm_sands',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/palm-sands-hero.webp',
    mainImage: '/images/projects/palm-sands-main.webp',
    gallery: [
      '/images/projects/palm-sands-1.webp',
      '/images/projects/palm-sands-2.webp',
      '/images/projects/palm-sands-3.webp',
      '/images/projects/palm-sands-4.webp',
      '/images/projects/palm-sands-5.webp',
      '/images/projects/palm-sands-6.webp',
      '/images/projects/palm-sands-7.webp',
      '/images/projects/palm-sands-8.webp',
      '/images/projects/palm-sands-9.webp',
      '/images/projects/palm-sands-10.webp',
      '/images/projects/palm-sands-11.webp',
      '/images/projects/palm-sands-12.webp',
      '/images/projects/palm-sands-13.webp',
      '/images/projects/palm-sands-14.webp',
      '/images/projects/palm-sands-15.webp',
      '/images/projects/palm-sands-16.webp',
      '/images/projects/palm-sands-17.webp',
      '/images/projects/palm-sands-18.webp',
      '/images/projects/palm-sands-19.webp',
      '/images/projects/palm-sands-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 16,
    slug: 'rc-mandani-loft',
    translationKey: 'rc_mandani_loft',
    year: '2024',
    location: 'Cebu',
    lat: 10.3157,
    lng: 123.9223,
    heroImage: '/images/projects/rc-mandani-loft-hero.webp',
    mainImage: '/images/projects/rc-mandani-loft-main.webp',
    gallery: [
      '/images/projects/rc-mandani-loft-1.webp',
      '/images/projects/rc-mandani-loft-2.webp',
      '/images/projects/rc-mandani-loft-3.webp',
      '/images/projects/rc-mandani-loft-4.webp',
      '/images/projects/rc-mandani-loft-5.webp',
      '/images/projects/rc-mandani-loft-6.webp',
      '/images/projects/rc-mandani-loft-7.webp',
      '/images/projects/rc-mandani-loft-8.webp',
      '/images/projects/rc-mandani-loft-9.webp',
      '/images/projects/rc-mandani-loft-10.webp',
      '/images/projects/rc-mandani-loft-11.webp',
      '/images/projects/rc-mandani-loft-12.webp',
      '/images/projects/rc-mandani-loft-13.webp',
      '/images/projects/rc-mandani-loft-14.webp',
      '/images/projects/rc-mandani-loft-15.webp',
      '/images/projects/rc-mandani-loft-16.webp',
      '/images/projects/rc-mandani-loft-17.webp',
      '/images/projects/rc-mandani-loft-18.webp',
      '/images/projects/rc-mandani-loft-19.webp',
      '/images/projects/rc-mandani-loft-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 17,
    slug: 'rosales-residence',
    translationKey: 'rosales_residence',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/rosales-residence-hero.webp',
    mainImage: '/images/projects/rosales-residence-main.webp',
    gallery: [
      '/images/projects/rosales-residence-1.webp',
      '/images/projects/rosales-residence-2.webp',
      '/images/projects/rosales-residence-3.webp',
      '/images/projects/rosales-residence-4.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 18,
    slug: 'squareview',
    translationKey: 'squareview',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/squareview-hero.webp',
    mainImage: '/images/projects/squareview-main.webp',
    gallery: [
      '/images/projects/squareview-1.webp',
      '/images/projects/squareview-2.webp',
      '/images/projects/squareview-3.webp',
      '/images/projects/squareview-4.webp',
      '/images/projects/squareview-5.webp',
      '/images/projects/squareview-6.webp',
      '/images/projects/squareview-7.webp',
      '/images/projects/squareview-8.webp',
      '/images/projects/squareview-9.webp',
      '/images/projects/squareview-10.webp',
      '/images/projects/squareview-11.webp',
      '/images/projects/squareview-12.webp',
      '/images/projects/squareview-13.webp',
      '/images/projects/squareview-14.webp',
      '/images/projects/squareview-15.webp',
      '/images/projects/squareview-16.webp',
      '/images/projects/squareview-17.webp',
      '/images/projects/squareview-18.webp',
      '/images/projects/squareview-19.webp',
      '/images/projects/squareview-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 19,
    slug: 'vmc-admin',
    translationKey: 'vmc_admin',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/vmc-admin-hero.webp',
    mainImage: '/images/projects/vmc-admin-main.webp',
    gallery: [
      '/images/projects/vmc-admin-1.webp',
      '/images/projects/vmc-admin-2.webp',
      '/images/projects/vmc-admin-3.webp',
      '/images/projects/vmc-admin-4.webp',
      '/images/projects/vmc-admin-5.webp',
      '/images/projects/vmc-admin-6.webp',
      '/images/projects/vmc-admin-7.webp',
      '/images/projects/vmc-admin-8.webp',
      '/images/projects/vmc-admin-9.webp',
      '/images/projects/vmc-admin-10.webp',
      '/images/projects/vmc-admin-11.webp',
      '/images/projects/vmc-admin-12.webp',
      '/images/projects/vmc-admin-13.webp',
      '/images/projects/vmc-admin-14.webp',
      '/images/projects/vmc-admin-15.webp',
      '/images/projects/vmc-admin-16.webp',
      '/images/projects/vmc-admin-17.webp',
      '/images/projects/vmc-admin-18.webp',
      '/images/projects/vmc-admin-19.webp',
      '/images/projects/vmc-admin-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 20,
    slug: 'vmc-housing',
    translationKey: 'vmc_housing',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/vmc-housing-hero.webp',
    mainImage: '/images/projects/vmc-housing-main.webp',
    gallery: [
      '/images/projects/vmc-housing-1.webp',
      '/images/projects/vmc-housing-2.webp',
      '/images/projects/vmc-housing-3.webp',
      '/images/projects/vmc-housing-4.webp',
      '/images/projects/vmc-housing-5.webp',
      '/images/projects/vmc-housing-6.webp',
      '/images/projects/vmc-housing-7.webp',
      '/images/projects/vmc-housing-8.webp',
      '/images/projects/vmc-housing-9.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 21,
    slug: 'vmc-projects',
    translationKey: 'vmc_projects',
    year: '2024',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/vmc-projects-hero.webp',
    mainImage: '/images/projects/vmc-projects-main.webp',
    gallery: [
      '/images/projects/vmc-projects-1.webp',
      '/images/projects/vmc-projects-2.webp',
      '/images/projects/vmc-projects-3.webp',
      '/images/projects/vmc-projects-4.webp',
      '/images/projects/vmc-projects-5.webp',
      '/images/projects/vmc-projects-6.webp',
      '/images/projects/vmc-projects-7.webp',
      '/images/projects/vmc-projects-8.webp',
      '/images/projects/vmc-projects-9.webp',
      '/images/projects/vmc-projects-10.webp',
      '/images/projects/vmc-projects-11.webp',
      '/images/projects/vmc-projects-12.webp',
      '/images/projects/vmc-projects-13.webp',
      '/images/projects/vmc-projects-14.webp',
      '/images/projects/vmc-projects-15.webp',
      '/images/projects/vmc-projects-16.webp',
      '/images/projects/vmc-projects-17.webp',
      '/images/projects/vmc-projects-18.webp',
      '/images/projects/vmc-projects-19.webp',
      '/images/projects/vmc-projects-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 22,
    slug: 'choa-unit-16c',
    translationKey: 'choa_unit_16c',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/choa-unit-16c-hero.webp',
    mainImage: '/images/projects/choa-unit-16c-main.webp',
    gallery: [
      '/images/projects/choa-unit-16c-1.webp',
      '/images/projects/choa-unit-16c-2.webp',
      '/images/projects/choa-unit-16c-3.webp',
      '/images/projects/choa-unit-16c-4.webp',
      '/images/projects/choa-unit-16c-5.webp',
      '/images/projects/choa-unit-16c-6.webp',
      '/images/projects/choa-unit-16c-7.webp',
      '/images/projects/choa-unit-16c-8.webp',
      '/images/projects/choa-unit-16c-9.webp',
      '/images/projects/choa-unit-16c-10.webp',
      '/images/projects/choa-unit-16c-11.webp',
      '/images/projects/choa-unit-16c-12.webp',
      '/images/projects/choa-unit-16c-13.webp',
      '/images/projects/choa-unit-16c-14.webp',
      '/images/projects/choa-unit-16c-15.webp',
      '/images/projects/choa-unit-16c-16.webp',
      '/images/projects/choa-unit-16c-17.webp',
      '/images/projects/choa-unit-16c-18.webp',
      '/images/projects/choa-unit-16c-19.webp',
      '/images/projects/choa-unit-16c-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 23,
    slug: 'graphic-junior-hotel',
    translationKey: 'graphic_junior_hotel',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/graphic-junior-hotel-hero.webp',
    mainImage: '/images/projects/graphic-junior-hotel-main.webp',
    gallery: [
      '/images/projects/graphic-junior-hotel-1.webp',
      '/images/projects/graphic-junior-hotel-2.webp',
      '/images/projects/graphic-junior-hotel-3.webp',
      '/images/projects/graphic-junior-hotel-4.webp',
      '/images/projects/graphic-junior-hotel-5.webp',
      '/images/projects/graphic-junior-hotel-6.webp',
      '/images/projects/graphic-junior-hotel-7.webp',
      '/images/projects/graphic-junior-hotel-8.webp',
      '/images/projects/graphic-junior-hotel-9.webp',
      '/images/projects/graphic-junior-hotel-10.webp',
      '/images/projects/graphic-junior-hotel-11.webp',
      '/images/projects/graphic-junior-hotel-12.webp',
      '/images/projects/graphic-junior-hotel-13.webp',
      '/images/projects/graphic-junior-hotel-14.webp',
      '/images/projects/graphic-junior-hotel-15.webp',
      '/images/projects/graphic-junior-hotel-16.webp',
      '/images/projects/graphic-junior-hotel-17.webp',
      '/images/projects/graphic-junior-hotel-18.webp',
      '/images/projects/graphic-junior-hotel-19.webp',
      '/images/projects/graphic-junior-hotel-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 24,
    slug: 'cafe-207',
    translationKey: 'cafe_207',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/cafe-207-hero.webp',
    mainImage: '/images/projects/cafe-207-main.webp',
    gallery: [
      '/images/projects/cafe-207-1.webp',
      '/images/projects/cafe-207-2.webp',
      '/images/projects/cafe-207-3.webp',
      '/images/projects/cafe-207-4.webp',
      '/images/projects/cafe-207-5.webp',
      '/images/projects/cafe-207-6.webp',
      '/images/projects/cafe-207-7.webp',
      '/images/projects/cafe-207-8.webp',
      '/images/projects/cafe-207-9.webp',
      '/images/projects/cafe-207-10.webp',
      '/images/projects/cafe-207-11.webp',
      '/images/projects/cafe-207-12.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 25,
    slug: 'byd-butuan',
    translationKey: 'byd_butuan',
    year: '2025',
    location: 'Butuan',
    lat: 8.9475,
    lng: 125.5406,
    heroImage: '/images/projects/byd-butuan-hero.webp',
    mainImage: '/images/projects/byd-butuan-main.webp',
    gallery: [
      '/images/projects/byd-butuan-1.webp',
      '/images/projects/byd-butuan-2.webp',
      '/images/projects/byd-butuan-3.webp',
      '/images/projects/byd-butuan-4.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 26,
    slug: 'byd-c5-acropolis',
    translationKey: 'byd_c5_acropolis',
    year: '2025',
    location: 'Manila',
    lat: 14.5995,
    lng: 120.9842,
    heroImage: '/images/projects/byd-c5-acropolis-hero.webp',
    mainImage: '/images/projects/byd-c5-acropolis-main.webp',
    gallery: [
      '/images/projects/byd-c5-acropolis-1.webp',
      '/images/projects/byd-c5-acropolis-2.webp',
      '/images/projects/byd-c5-acropolis-3.webp',
      '/images/projects/byd-c5-acropolis-4.webp',
      '/images/projects/byd-c5-acropolis-5.webp',
      '/images/projects/byd-c5-acropolis-6.webp',
      '/images/projects/byd-c5-acropolis-7.webp',
      '/images/projects/byd-c5-acropolis-8.webp',
      '/images/projects/byd-c5-acropolis-9.webp',
      '/images/projects/byd-c5-acropolis-10.webp',
      '/images/projects/byd-c5-acropolis-11.webp',
      '/images/projects/byd-c5-acropolis-12.webp',
      '/images/projects/byd-c5-acropolis-13.webp',
      '/images/projects/byd-c5-acropolis-14.webp',
      '/images/projects/byd-c5-acropolis-15.webp',
      '/images/projects/byd-c5-acropolis-16.webp',
      '/images/projects/byd-c5-acropolis-17.webp',
      '/images/projects/byd-c5-acropolis-18.webp',
      '/images/projects/byd-c5-acropolis-19.webp',
      '/images/projects/byd-c5-acropolis-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 27,
    slug: 'byd-iligan',
    translationKey: 'byd_iligan',
    year: '2025',
    location: 'Iligan',
    lat: 8.228,
    lng: 124.2452,
    heroImage: '/images/projects/byd-iligan-hero.webp',
    mainImage: '/images/projects/byd-iligan-main.webp',
    gallery: [
      '/images/projects/byd-iligan-1.webp',
      '/images/projects/byd-iligan-2.webp',
      '/images/projects/byd-iligan-3.webp',
      '/images/projects/byd-iligan-4.webp',
      '/images/projects/byd-iligan-5.webp',
      '/images/projects/byd-iligan-6.webp',
      '/images/projects/byd-iligan-7.webp',
      '/images/projects/byd-iligan-8.webp',
      '/images/projects/byd-iligan-9.webp',
      '/images/projects/byd-iligan-10.webp',
      '/images/projects/byd-iligan-11.webp',
      '/images/projects/byd-iligan-12.webp',
      '/images/projects/byd-iligan-13.webp',
      '/images/projects/byd-iligan-14.webp',
      '/images/projects/byd-iligan-15.webp',
      '/images/projects/byd-iligan-16.webp',
      '/images/projects/byd-iligan-17.webp',
      '/images/projects/byd-iligan-18.webp',
      '/images/projects/byd-iligan-19.webp',
      '/images/projects/byd-iligan-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 28,
    slug: 'byd-marikina',
    translationKey: 'byd_marikina',
    year: '2025',
    location: 'Manila',
    lat: 14.5995,
    lng: 120.9842,
    heroImage: '/images/projects/byd-marikina-hero.webp',
    mainImage: '/images/projects/byd-marikina-main.webp',
    gallery: [
      '/images/projects/byd-marikina-1.webp',
      '/images/projects/byd-marikina-2.webp',
      '/images/projects/byd-marikina-3.webp',
      '/images/projects/byd-marikina-4.webp',
      '/images/projects/byd-marikina-5.webp',
      '/images/projects/byd-marikina-6.webp',
      '/images/projects/byd-marikina-7.webp',
      '/images/projects/byd-marikina-8.webp',
      '/images/projects/byd-marikina-9.webp',
      '/images/projects/byd-marikina-10.webp',
      '/images/projects/byd-marikina-11.webp',
      '/images/projects/byd-marikina-12.webp',
      '/images/projects/byd-marikina-13.webp',
      '/images/projects/byd-marikina-14.webp',
      '/images/projects/byd-marikina-15.webp',
      '/images/projects/byd-marikina-16.webp',
      '/images/projects/byd-marikina-17.webp',
      '/images/projects/byd-marikina-18.webp',
      '/images/projects/byd-marikina-19.webp',
      '/images/projects/byd-marikina-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 29,
    slug: 'balisbis-residence',
    translationKey: 'balisbis_residence',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/balisbis-residence-hero.webp',
    mainImage: '/images/projects/balisbis-residence-main.webp',
    gallery: [
      '/images/projects/balisbis-residence-1.webp',
      '/images/projects/balisbis-residence-2.webp',
      '/images/projects/balisbis-residence-3.webp',
      '/images/projects/balisbis-residence-4.webp',
      '/images/projects/balisbis-residence-5.webp',
      '/images/projects/balisbis-residence-6.webp',
      '/images/projects/balisbis-residence-7.webp',
      '/images/projects/balisbis-residence-8.webp',
      '/images/projects/balisbis-residence-9.webp',
      '/images/projects/balisbis-residence-10.webp',
      '/images/projects/balisbis-residence-11.webp',
      '/images/projects/balisbis-residence-12.webp',
      '/images/projects/balisbis-residence-13.webp',
      '/images/projects/balisbis-residence-14.webp',
      '/images/projects/balisbis-residence-15.webp',
      '/images/projects/balisbis-residence-16.webp',
      '/images/projects/balisbis-residence-17.webp',
      '/images/projects/balisbis-residence-18.webp',
      '/images/projects/balisbis-residence-19.webp',
      '/images/projects/balisbis-residence-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 30,
    slug: 'bellarie-office',
    translationKey: 'bellarie_office',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/bellarie-office-hero.webp',
    mainImage: '/images/projects/bellarie-office-main.webp',
    gallery: [
      '/images/projects/bellarie-office-1.webp',
      '/images/projects/bellarie-office-2.webp',
      '/images/projects/bellarie-office-3.webp',
      '/images/projects/bellarie-office-4.webp',
      '/images/projects/bellarie-office-5.webp',
      '/images/projects/bellarie-office-6.webp',
      '/images/projects/bellarie-office-7.webp',
      '/images/projects/bellarie-office-8.webp',
      '/images/projects/bellarie-office-9.webp',
      '/images/projects/bellarie-office-10.webp',
      '/images/projects/bellarie-office-11.webp',
      '/images/projects/bellarie-office-12.webp',
      '/images/projects/bellarie-office-13.webp',
      '/images/projects/bellarie-office-14.webp',
      '/images/projects/bellarie-office-15.webp',
      '/images/projects/bellarie-office-16.webp',
      '/images/projects/bellarie-office-17.webp',
      '/images/projects/bellarie-office-18.webp',
      '/images/projects/bellarie-office-19.webp',
      '/images/projects/bellarie-office-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 31,
    slug: 'blush',
    translationKey: 'blush',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/blush-hero.webp',
    mainImage: '/images/projects/blush-main.webp',
    gallery: [
      '/images/projects/blush-1.webp',
      '/images/projects/blush-2.webp',
      '/images/projects/blush-3.webp',
      '/images/projects/blush-4.webp',
      '/images/projects/blush-5.webp',
      '/images/projects/blush-6.webp',
      '/images/projects/blush-7.webp',
      '/images/projects/blush-8.webp',
      '/images/projects/blush-9.webp',
      '/images/projects/blush-10.webp',
      '/images/projects/blush-11.webp',
      '/images/projects/blush-12.webp',
      '/images/projects/blush-13.webp',
      '/images/projects/blush-14.webp',
      '/images/projects/blush-15.webp',
      '/images/projects/blush-16.webp',
      '/images/projects/blush-17.webp',
      '/images/projects/blush-18.webp',
      '/images/projects/blush-19.webp',
      '/images/projects/blush-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 32,
    slug: 'dasmarinas-residence',
    translationKey: 'dasmarinas_residence',
    year: '2025',
    location: 'Cavite',
    lat: 14.3294,
    lng: 120.9367,
    heroImage: '/images/projects/dasmarinas-residence-hero.webp',
    mainImage: '/images/projects/dasmarinas-residence-main.webp',
    gallery: [
      '/images/projects/dasmarinas-residence-1.webp',
      '/images/projects/dasmarinas-residence-2.webp',
      '/images/projects/dasmarinas-residence-3.webp',
      '/images/projects/dasmarinas-residence-4.webp',
      '/images/projects/dasmarinas-residence-5.webp',
      '/images/projects/dasmarinas-residence-6.webp',
      '/images/projects/dasmarinas-residence-7.webp',
      '/images/projects/dasmarinas-residence-8.webp',
      '/images/projects/dasmarinas-residence-9.webp',
      '/images/projects/dasmarinas-residence-10.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 33,
    slug: 'denza-showroom',
    translationKey: 'denza_showroom',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/denza-showroom-hero.webp',
    mainImage: '/images/projects/denza-showroom-main.webp',
    gallery: [
      '/images/projects/denza-showroom-1.webp',
      '/images/projects/denza-showroom-2.webp',
      '/images/projects/denza-showroom-3.webp',
      '/images/projects/denza-showroom-4.webp',
      '/images/projects/denza-showroom-5.webp',
      '/images/projects/denza-showroom-6.webp',
      '/images/projects/denza-showroom-7.webp',
      '/images/projects/denza-showroom-8.webp',
      '/images/projects/denza-showroom-9.webp',
      '/images/projects/denza-showroom-10.webp',
      '/images/projects/denza-showroom-11.webp',
      '/images/projects/denza-showroom-12.webp',
      '/images/projects/denza-showroom-13.webp',
      '/images/projects/denza-showroom-14.webp',
      '/images/projects/denza-showroom-15.webp',
      '/images/projects/denza-showroom-16.webp',
      '/images/projects/denza-showroom-17.webp',
      '/images/projects/denza-showroom-18.webp',
      '/images/projects/denza-showroom-19.webp',
      '/images/projects/denza-showroom-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 34,
    slug: 'foxhomes-2025',
    translationKey: 'foxhomes_2025',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/foxhomes-2025-hero.webp',
    mainImage: '/images/projects/foxhomes-2025-main.webp',
    gallery: [
      '/images/projects/foxhomes-2025-1.webp',
      '/images/projects/foxhomes-2025-2.webp',
      '/images/projects/foxhomes-2025-3.webp',
      '/images/projects/foxhomes-2025-4.webp',
      '/images/projects/foxhomes-2025-5.webp',
      '/images/projects/foxhomes-2025-6.webp',
      '/images/projects/foxhomes-2025-7.webp',
      '/images/projects/foxhomes-2025-8.webp',
      '/images/projects/foxhomes-2025-9.webp',
      '/images/projects/foxhomes-2025-10.webp',
      '/images/projects/foxhomes-2025-11.webp',
      '/images/projects/foxhomes-2025-12.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 35,
    slug: 'graphic-annex',
    translationKey: 'graphic_annex',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/graphic-annex-hero.webp',
    mainImage: '/images/projects/graphic-annex-main.webp',
    gallery: [
      '/images/projects/graphic-annex-1.webp',
      '/images/projects/graphic-annex-2.webp',
      '/images/projects/graphic-annex-3.webp',
      '/images/projects/graphic-annex-4.webp',
      '/images/projects/graphic-annex-5.webp',
      '/images/projects/graphic-annex-6.webp',
      '/images/projects/graphic-annex-7.webp',
      '/images/projects/graphic-annex-8.webp',
      '/images/projects/graphic-annex-9.webp',
      '/images/projects/graphic-annex-10.webp',
      '/images/projects/graphic-annex-11.webp',
      '/images/projects/graphic-annex-12.webp',
      '/images/projects/graphic-annex-13.webp',
      '/images/projects/graphic-annex-14.webp',
      '/images/projects/graphic-annex-15.webp',
      '/images/projects/graphic-annex-16.webp',
      '/images/projects/graphic-annex-17.webp',
      '/images/projects/graphic-annex-18.webp',
      '/images/projects/graphic-annex-19.webp',
      '/images/projects/graphic-annex-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 36,
    slug: 'ozamiz-dialysis-center',
    translationKey: 'ozamiz_dialysis_center',
    year: '2025',
    location: 'Ozamiz',
    lat: 8.15,
    lng: 123.85,
    heroImage: '/images/projects/ozamiz-dialysis-center-hero.webp',
    mainImage: '/images/projects/ozamiz-dialysis-center-main.webp',
    gallery: [
      '/images/projects/ozamiz-dialysis-center-1.webp',
      '/images/projects/ozamiz-dialysis-center-2.webp',
      '/images/projects/ozamiz-dialysis-center-3.webp',
      '/images/projects/ozamiz-dialysis-center-4.webp',
      '/images/projects/ozamiz-dialysis-center-5.webp',
      '/images/projects/ozamiz-dialysis-center-6.webp',
      '/images/projects/ozamiz-dialysis-center-7.webp',
      '/images/projects/ozamiz-dialysis-center-8.webp',
      '/images/projects/ozamiz-dialysis-center-9.webp',
      '/images/projects/ozamiz-dialysis-center-10.webp',
      '/images/projects/ozamiz-dialysis-center-11.webp',
      '/images/projects/ozamiz-dialysis-center-12.webp',
      '/images/projects/ozamiz-dialysis-center-13.webp',
      '/images/projects/ozamiz-dialysis-center-14.webp',
      '/images/projects/ozamiz-dialysis-center-15.webp',
      '/images/projects/ozamiz-dialysis-center-16.webp',
      '/images/projects/ozamiz-dialysis-center-17.webp',
      '/images/projects/ozamiz-dialysis-center-18.webp',
      '/images/projects/ozamiz-dialysis-center-19.webp',
      '/images/projects/ozamiz-dialysis-center-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 37,
    slug: 'raintree-beauty-clinic',
    translationKey: 'raintree_beauty_clinic',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/raintree-beauty-clinic-hero.webp',
    mainImage: '/images/projects/raintree-beauty-clinic-main.webp',
    gallery: [
      '/images/projects/raintree-beauty-clinic-1.webp',
      '/images/projects/raintree-beauty-clinic-2.webp',
      '/images/projects/raintree-beauty-clinic-3.webp',
      '/images/projects/raintree-beauty-clinic-4.webp',
      '/images/projects/raintree-beauty-clinic-5.webp',
      '/images/projects/raintree-beauty-clinic-6.webp',
      '/images/projects/raintree-beauty-clinic-7.webp',
      '/images/projects/raintree-beauty-clinic-8.webp',
      '/images/projects/raintree-beauty-clinic-9.webp',
      '/images/projects/raintree-beauty-clinic-10.webp',
      '/images/projects/raintree-beauty-clinic-11.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 38,
    slug: 'sanjus-diagnostics',
    translationKey: 'sanjus_diagnostics',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/sanjus-diagnostics-hero.webp',
    mainImage: '/images/projects/sanjus-diagnostics-main.webp',
    gallery: [
      '/images/projects/sanjus-diagnostics-1.webp',
      '/images/projects/sanjus-diagnostics-2.webp',
      '/images/projects/sanjus-diagnostics-3.webp',
      '/images/projects/sanjus-diagnostics-4.webp',
      '/images/projects/sanjus-diagnostics-5.webp',
      '/images/projects/sanjus-diagnostics-6.webp',
      '/images/projects/sanjus-diagnostics-7.webp',
      '/images/projects/sanjus-diagnostics-8.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 39,
    slug: 'sorana-island-villas',
    translationKey: 'sorana_island_villas',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/sorana-island-villas-hero.webp',
    mainImage: '/images/projects/sorana-island-villas-main.webp',
    gallery: [
      '/images/projects/sorana-island-villas-1.webp',
      '/images/projects/sorana-island-villas-2.webp',
      '/images/projects/sorana-island-villas-3.webp',
      '/images/projects/sorana-island-villas-4.webp',
      '/images/projects/sorana-island-villas-5.webp',
      '/images/projects/sorana-island-villas-6.webp',
      '/images/projects/sorana-island-villas-7.webp',
      '/images/projects/sorana-island-villas-8.webp',
      '/images/projects/sorana-island-villas-9.webp',
      '/images/projects/sorana-island-villas-10.webp',
      '/images/projects/sorana-island-villas-11.webp',
      '/images/projects/sorana-island-villas-12.webp',
      '/images/projects/sorana-island-villas-13.webp',
      '/images/projects/sorana-island-villas-14.webp',
      '/images/projects/sorana-island-villas-15.webp',
      '/images/projects/sorana-island-villas-16.webp',
      '/images/projects/sorana-island-villas-17.webp',
      '/images/projects/sorana-island-villas-18.webp',
      '/images/projects/sorana-island-villas-19.webp',
      '/images/projects/sorana-island-villas-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 40,
    slug: 'sytin-projects',
    translationKey: 'sytin_projects',
    year: '2025',
    location: 'Manila',
    lat: 14.5995,
    lng: 120.9842,
    heroImage: '/images/projects/sytin-projects-hero.webp',
    mainImage: '/images/projects/sytin-projects-main.webp',
    gallery: [
      '/images/projects/sytin-projects-1.webp',
      '/images/projects/sytin-projects-2.webp',
      '/images/projects/sytin-projects-3.webp',
      '/images/projects/sytin-projects-4.webp',
      '/images/projects/sytin-projects-5.webp',
      '/images/projects/sytin-projects-6.webp',
      '/images/projects/sytin-projects-7.webp',
      '/images/projects/sytin-projects-8.webp',
      '/images/projects/sytin-projects-9.webp',
      '/images/projects/sytin-projects-10.webp',
      '/images/projects/sytin-projects-11.webp',
      '/images/projects/sytin-projects-12.webp',
      '/images/projects/sytin-projects-13.webp',
      '/images/projects/sytin-projects-14.webp',
      '/images/projects/sytin-projects-15.webp',
      '/images/projects/sytin-projects-16.webp',
      '/images/projects/sytin-projects-17.webp',
      '/images/projects/sytin-projects-18.webp',
      '/images/projects/sytin-projects-19.webp',
      '/images/projects/sytin-projects-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 41,
    slug: 'tabas',
    translationKey: 'tabas',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/tabas-hero.webp',
    mainImage: '/images/projects/tabas-main.webp',
    gallery: [
      '/images/projects/tabas-1.webp',
      '/images/projects/tabas-2.webp',
      '/images/projects/tabas-3.webp',
      '/images/projects/tabas-4.webp',
      '/images/projects/tabas-5.webp',
      '/images/projects/tabas-6.webp',
      '/images/projects/tabas-7.webp',
      '/images/projects/tabas-8.webp',
      '/images/projects/tabas-9.webp',
      '/images/projects/tabas-10.webp',
      '/images/projects/tabas-11.webp',
      '/images/projects/tabas-12.webp',
      '/images/projects/tabas-13.webp',
      '/images/projects/tabas-14.webp',
      '/images/projects/tabas-15.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 42,
    slug: 'vmc-projects-2025',
    translationKey: 'vmc_projects_2025',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/vmc-projects-2025-hero.webp',
    mainImage: '/images/projects/vmc-projects-2025-main.webp',
    gallery: [
      '/images/projects/vmc-projects-2025-1.webp',
      '/images/projects/vmc-projects-2025-2.webp',
      '/images/projects/vmc-projects-2025-3.webp',
      '/images/projects/vmc-projects-2025-4.webp',
      '/images/projects/vmc-projects-2025-5.webp',
      '/images/projects/vmc-projects-2025-6.webp',
      '/images/projects/vmc-projects-2025-7.webp',
      '/images/projects/vmc-projects-2025-8.webp',
      '/images/projects/vmc-projects-2025-9.webp',
      '/images/projects/vmc-projects-2025-10.webp',
      '/images/projects/vmc-projects-2025-11.webp',
      '/images/projects/vmc-projects-2025-12.webp',
      '/images/projects/vmc-projects-2025-13.webp',
      '/images/projects/vmc-projects-2025-14.webp',
      '/images/projects/vmc-projects-2025-15.webp',
      '/images/projects/vmc-projects-2025-16.webp',
      '/images/projects/vmc-projects-2025-17.webp',
      '/images/projects/vmc-projects-2025-18.webp',
      '/images/projects/vmc-projects-2025-19.webp',
      '/images/projects/vmc-projects-2025-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 43,
    slug: 'yang-residence',
    translationKey: 'yang_residence',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/yang-residence-hero.webp',
    mainImage: '/images/projects/yang-residence-main.webp',
    gallery: [
      '/images/projects/yang-residence-1.webp',
      '/images/projects/yang-residence-2.webp',
      '/images/projects/yang-residence-3.webp',
      '/images/projects/yang-residence-4.webp',
      '/images/projects/yang-residence-5.webp',
      '/images/projects/yang-residence-6.webp',
      '/images/projects/yang-residence-7.webp',
      '/images/projects/yang-residence-8.webp',
      '/images/projects/yang-residence-9.webp',
      '/images/projects/yang-residence-10.webp',
      '/images/projects/yang-residence-11.webp',
      '/images/projects/yang-residence-12.webp',
      '/images/projects/yang-residence-13.webp',
      '/images/projects/yang-residence-14.webp',
      '/images/projects/yang-residence-15.webp',
      '/images/projects/yang-residence-16.webp',
      '/images/projects/yang-residence-17.webp',
      '/images/projects/yang-residence-18.webp',
      '/images/projects/yang-residence-19.webp',
      '/images/projects/yang-residence-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 44,
    slug: 'yap-residences-interiors',
    translationKey: 'yap_residences_interiors',
    year: '2025',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/yap-residences-interiors-hero.webp',
    mainImage: '/images/projects/yap-residences-interiors-main.webp',
    gallery: [
      '/images/projects/yap-residences-interiors-1.webp',
      '/images/projects/yap-residences-interiors-2.webp',
      '/images/projects/yap-residences-interiors-3.webp',
      '/images/projects/yap-residences-interiors-4.webp',
      '/images/projects/yap-residences-interiors-5.webp',
      '/images/projects/yap-residences-interiors-6.webp',
      '/images/projects/yap-residences-interiors-7.webp',
      '/images/projects/yap-residences-interiors-8.webp',
      '/images/projects/yap-residences-interiors-9.webp',
      '/images/projects/yap-residences-interiors-10.webp',
      '/images/projects/yap-residences-interiors-11.webp',
      '/images/projects/yap-residences-interiors-12.webp',
      '/images/projects/yap-residences-interiors-13.webp',
      '/images/projects/yap-residences-interiors-14.webp',
      '/images/projects/yap-residences-interiors-15.webp',
      '/images/projects/yap-residences-interiors-16.webp',
      '/images/projects/yap-residences-interiors-17.webp',
      '/images/projects/yap-residences-interiors-18.webp',
      '/images/projects/yap-residences-interiors-19.webp',
      '/images/projects/yap-residences-interiors-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 45,
    slug: 'baic-radar-cdo',
    translationKey: 'baic_radar_cdo',
    year: '2026',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/baic-radar-cdo-hero.webp',
    mainImage: '/images/projects/baic-radar-cdo-main.webp',
    gallery: [
      '/images/projects/baic-radar-cdo-1.webp',
      '/images/projects/baic-radar-cdo-2.webp',
      '/images/projects/baic-radar-cdo-3.webp',
      '/images/projects/baic-radar-cdo-4.webp',
      '/images/projects/baic-radar-cdo-5.webp',
      '/images/projects/baic-radar-cdo-6.webp',
      '/images/projects/baic-radar-cdo-7.webp',
      '/images/projects/baic-radar-cdo-8.webp',
      '/images/projects/baic-radar-cdo-9.webp',
      '/images/projects/baic-radar-cdo-10.webp',
      '/images/projects/baic-radar-cdo-11.webp',
      '/images/projects/baic-radar-cdo-12.webp',
      '/images/projects/baic-radar-cdo-13.webp',
      '/images/projects/baic-radar-cdo-14.webp',
      '/images/projects/baic-radar-cdo-15.webp',
      '/images/projects/baic-radar-cdo-16.webp',
      '/images/projects/baic-radar-cdo-17.webp',
      '/images/projects/baic-radar-cdo-18.webp',
      '/images/projects/baic-radar-cdo-19.webp',
      '/images/projects/baic-radar-cdo-20.webp',
    ],
    floorPlanImages: [],
  },
  {
    id: 46,
    slug: 'chen-residence',
    translationKey: 'chen_residence',
    year: '2026',
    location: 'CDO',
    lat: 8.4797,
    lng: 124.6525,
    heroImage: '/images/projects/chen-residence-hero.webp',
    mainImage: '/images/projects/chen-residence-main.webp',
    gallery: [
      '/images/projects/chen-residence-1.webp',
      '/images/projects/chen-residence-2.webp',
      '/images/projects/chen-residence-3.webp',
      '/images/projects/chen-residence-4.webp',
      '/images/projects/chen-residence-5.webp',
      '/images/projects/chen-residence-6.webp',
      '/images/projects/chen-residence-7.webp',
      '/images/projects/chen-residence-8.webp',
      '/images/projects/chen-residence-9.webp',
      '/images/projects/chen-residence-10.webp',
      '/images/projects/chen-residence-11.webp',
      '/images/projects/chen-residence-12.webp',
      '/images/projects/chen-residence-13.webp',
      '/images/projects/chen-residence-14.webp',
      '/images/projects/chen-residence-15.webp',
      '/images/projects/chen-residence-16.webp',
      '/images/projects/chen-residence-17.webp',
      '/images/projects/chen-residence-18.webp',
      '/images/projects/chen-residence-19.webp',
    ],
    floorPlanImages: [],
  },
];

export { projectsData };

export default function ProjectDetailPage() {
  const { slug } = useParams<{ slug: string }>();
  const navigate = useNavigate();
  const { t } = useTranslation();

  const project = projectsData.find((p) => p.slug === slug);

  if (!project) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="text-center">
          <p className="text-black/40 text-sm mb-4" style={{ fontFamily: 'Geist, sans-serif' }}>
            {t('detail_not_found')}
          </p>
          <button
            onClick={() => navigate('/projects')}
            className="text-black text-sm underline cursor-pointer"
            style={{ fontFamily: 'Geist, sans-serif' }}
          >
            {t('detail_back_link')}
          </button>
        </div>
      </div>
    );
  }

  const tk = project.translationKey;
  const name = t(`proj_${tk}_name`);
  const address = t(`proj_${tk}_address`);
  const category = t(`proj_${tk}_category`);
  const description = t(`proj_${tk}_description`);
  const quote = t(`proj_${tk}_quote`, { defaultValue: '' });
  const floorPlans = project.floorPlanImages.map((img, i) => ({
    label: t(`proj_${tk}_fp${i}`),
    image: img,
  }));

  const currentIndex = projectsData.findIndex((p) => p.slug === slug);
  const nextProject = projectsData[(currentIndex + 1) % projectsData.length];
  const prevProject = projectsData[(currentIndex - 1 + projectsData.length) % projectsData.length];
  const nextName = t(`proj_${nextProject.translationKey}_name`);
  const prevName = t(`proj_${prevProject.translationKey}_name`);
  const specs = projectSpecs[project.slug];

  return (
    <div className="min-h-screen bg-white">
      <Navigation theme="light" />

      <ProjectHero
        name={name}
        image={project.heroImage}
        index={currentIndex}
        total={projectsData.length}
        location={project.location}
      />

      {specs && (
        <div className="px-6 md:px-16 lg:px-24 mt-16 md:mt-24">
          <div className="mx-auto" style={{ maxWidth: '840px' }}>
            <ProjectSpecs
              plotArea={specs.plotArea}
              builtArea={specs.builtArea}
              floors={specs.floors}
              year={project.year}
            />
          </div>
        </div>
      )}

      <ProjectInfo
        key={project.slug}
        name={name}
        description={description}
        mainImage={project.mainImage}
        galleryImages={project.gallery}
        plans={floorPlans}
        quote={quote || undefined}
      />

      <div className="pb-8 md:pb-14" />

      <ProjectLocation
        lat={project.lat}
        lng={project.lng}
        name={name}
      />

      <NextProject
        slug={nextProject.slug}
        name={nextName}
        location={nextProject.location}
        heroImage={nextProject.heroImage}
        prevSlug={prevProject.slug}
        prevName={prevName}
      />

      <StudioCTA />
      <ContactFooter hideContactBar />
    </div>
  );
}
